export const CREATE_ACTION = "CREATE_ACTION";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAILED = "CREATE_FAILED";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_INFO = "USER_INFO";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const TRANSFER_ACTION= "TRANSFER_ACTION";
export const TRANSFER_SUCCESS= "TRANSFER_SUCCESS";
export const TRANSFER_FAILED= "TRANSFER_FAILED";

export const TRANSACTION_HISTORY_ACTION = "TRANSACTION_HISTORY_ACTION";
export const TRANSACTION_HISTORY_SUCCESS = "TRANSACTION_HISTORY_FAILED";
export const TRANSACTION_HISTORY_FAILED = "TRANSACTION_HISTORY_FAILED";

export const GET_USER_ACTION = "GET_USER_ACTION";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";



